### PR TITLE
PDF Handbook Added

### PR DESCRIPTION
**Pull request by mmertgunduz**
_Hello, I added a PDF handbook for the handbook.html file. You can check it and let me know._

The things I will add:

🟢 Handbook PDF (31/03/2022)
🔴 The whole website will be changed from HTML4 to HTML5. (Not Done)
🔴 CSS changes. (Not Done)
🔴 JS will be added. (Not Done)
🔴 Mobile Responsivity   (Not Done)
🔴 SEO operations (Not Done)

----------------------------------
🟢 --> Completed
🔴 --> Not Completed

### CODE REVIEW

**Comment by mrclksr** [comment]
Thank you for the pull request :-)

Just on thing: Did you add the .html files intentionally?

**Comment by mmertgunduz** [comment]
I wasn't sure to add or not. So I decided to add :-)

Do you want me to add only the .in files?

**Comment by mrclksr** [comment]
Ah, I see. The .html files are auto-generated from the .in files when running `make`, so they are not part of the repository. If you have any questions regarding the website build system, feel free to ask. We wouldn't mind a new build system written in Python either :-) or whatever you have in mind how to design it.

Regarding the pull request: Please remove the .html files and the Makefile from your fork, commit, and make a new pull request.

**Comment by mmertgunduz** [comment]
Ah got it! Thanks for the information.

Will do now, I can improve it from the existing system. Not a problem, it is always a better idea to develop a running system :-)

**Pull request closed without merging**
