### PR TITLE
Stylesheet Finished ✴

### PR DESCRIPTION
**Pull request by mmertgunduz**
_Hello, I finished the new stylesheet :-)_

The things I will add:

🟢 Handbook PDF (31/03/2022)
🟢  The whole website will be changed from HTML4 to HTML5 (15/04/2022)
🟢 Syntatic errors fixed (04/05/2022)
🟢 CSS changed (04/05/2022)
🔴 JS will be added. (Not Done)
🔴 Mobile Responsivity   (Not Done)
🔴 SEO operations (Not Done)

----------------------------------
🟢 --> Completed
🔴 --> Not Completed

### CODE REVIEW

**Comment by mrclksr** [comment]
Thank you, Mehmet! Excellent work :-)

**Comment by mmertgunduz** [comment]
Glad you like! That means a lot :-)

**Comment by mrclksr** [comment]
The website is online :-)

**Comment by mmertgunduz** [comment]
Looks great! Will add more stuff for extra mobile responsivity :-)

**Comment by bsdlme** [comment]
The website looks really nice now. Thank you for your effoerts, @MertGunduz

**Comment by mmertgunduz** [comment]
@bsdlme It's a pleasure to work! I will add more things such as mobile responsive stuff and some SEO stuff :-)

**Pull request merged**
